# Uncomment the next line to define a global platform for your project
 platform :ios, '14.5'

target 'HowITalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HowITalk

pod 'SnapKit', '~> 5.0.0'
pod 'Firebase/Analytics'
pod 'Firebase/RemoteConfig'
pod 'TextFieldEffects'

end
