# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'HowTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HowTalk


  pod 'SnapKit', '~> 5.0.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  pod 'TextFieldEffects'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

end
